In [ ]:
print('hi')

hi


In [ ]:
import numpy as np
list1=[1,2,3]
array1=np.array(list1)
print('list=',list1)
print('array=',array1)
type(list1)
type(array1)

list= [1, 2, 3]
array= [1 2 3]


numpy.ndarray

In [ ]:
type(list1)


list

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
import numpy as np
array1=np.array([10,20,30])
array2=np.array([2,2,2])

print("array2 multiplied by array1:",array1*array2)
print("array2 divided by array1:",array2/array1)
print("array2 raised to the power of array1:",array2**array1)
print("adding to numpy  as arrays(array1 and array2 together)",array1+array2)


array2 multiplied by array1: [20 40 60]
array2 divided by array1: [0.2        0.1        0.06666667]
array2 raised to the power of array1: [      1024    1048576 1073741824]
adding to numpy  as arrays(array1 and array2 together) [12 22 32]


In [ ]:
import numpy as np

def main():
    # Generate two arrays
    array1 = np.array([[1, 2, 3], [4, 5, 6]])
    array2 = np.array([[7, 8, 9], [10, 11, 12]])

    # Perform addition
    result_array = np.add(array1, array2)

    # Display the textual output
    print(f"Addition of two arrays:\n{array1} + {array2} =\n{result_array}")

if __name__ == "__main__":
    main()


Addition of two arrays:
[[1 2 3]
 [4 5 6]] + [[ 7  8  9]
 [10 11 12]] =
[[ 8 10 12]
 [14 16 18]]


In [ ]:
import numpy as np
array1=np.array([10,20,30])
#sine function
print("sine: ",np.sin(array1))
#logarithm
print("natural logarithm: ",np.log(array1))
print("base-10 logarithm: ",np.log10(array1))
print("base-2 logarithm: ",np.log2(array1))
#exponential
print("exponential: ",np.exp(array1))

sine:  [-0.54402111  0.91294525 -0.98803162]
natural logarithm:  [2.30258509 2.99573227 3.40119738]
base-10 logarithm:  [1.         1.30103    1.47712125]
base-2 logarithm:  [3.32192809 4.32192809 4.9068906 ]
exponential:  [2.20264658e+04 4.85165195e+08 1.06864746e+13]
